Eslint error fixed
OpenMined/syft.js pull request #104
Opened 2020-02-27 05:14 UTC by IamRavikantSingh

#103

2020-02-27 22:51 UTC, vvmnnnkv requested changes

2020-02-27 22:51 UTC, vvmnnnkv commented on package.json
> +    "babel-eslint": "^10.1.0",
Move to devdependencies

2020-02-27 22:51 UTC, vvmnnnkv commented on test/data_channel_message.test.js
> +    // const info2 = DataChannelMessage.messageInfoFromBuf(chunk2);
Can be just removed if not used anywhere

2020-02-27 22:51 UTC, vvmnnnkv commented on test/data_channel_message.test.js
> +    // const chunk2 = messageOrig.getChunk(1);
Can be just removed if not used anywhere

2020-02-27 22:51 UTC, vvmnnnkv commented on test/data_channel_message_queue.test.js
> +    // const info2 = DataChannelMessage.messageInfoFromBuf(chunk2);
Can be just removed

2020-02-28 10:12 UTC, cereallarceny commented
For the record, we won't be merging this PR until we have 100% passing tests. We don't need to have 100% test coverage, but we need all failing tests and linting errors to be resolved.

2020-02-28 11:57 UTC, IamRavikantSingh commented
> For the record, we won't be merging this PR until we have 100% passing tests. We don't need to have 100% test coverage, but we need all failing tests and linting errors to be resolved.

This pr only contains eslint error fix and for jest test fails I am working on another Pr #105

2020-03-01 14:48 UTC, vvmnnnkv approved these changes

2020-03-01 14:48 UTC, vvmnnnkv commented
Thanks!

2020-03-01 14:48 UTC, merged