Add training API
OpenMined/syft.js pull request #226
Opened 2020-09-07 14:54 UTC by vvmnnnkv

## Description
This PR implements changes described in #212 

## Affected Dependencies
n/a

## How has this been tested?
Added unit tests

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

2020-09-07 16:48 UTC, cereallarceny requested changes
Only minor changes. However @vvmnnnkv - I will no longer merge PR's without appropriate documentation changes. Please also supply changes in documentation to all the appropriate readmes both in this project and in others.

2020-09-07 16:48 UTC, cereallarceny commented on examples/mnist/index.js
> +      planInputs: [
Can we just call these `inputs`?

2020-09-07 16:48 UTC, cereallarceny commented on examples/mnist/index.js
> +      planOutputs: [
Can we just call these `outputs`?

2020-09-09 08:18 UTC, vvmnnnkv commented
Updated docs and added additional input spec type to easier reference values in PyGrid's client_config.

2020-09-09 09:50 UTC, cereallarceny approved these changes

2020-09-09 09:50 UTC, merged